// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3OQK5JsBD7hgRuInoBH5dJnv34iK7ujw',
    appId: '1:542509130475:web:9b165b6622d834935914ae',
    messagingSenderId: '542509130475',
    projectId: 'elemanyonlendir-6c6b7',
    authDomain: 'elemanyonlendir-6c6b7.firebaseapp.com',
    databaseURL: 'https://elemanyonlendir-6c6b7.firebaseio.com',
    storageBucket: 'elemanyonlendir-6c6b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo8M7-30gFnp-d6lMt5-oAsO2_w66tyCQ',
    appId: '1:542509130475:android:75fd77d7da0dba505914ae',
    messagingSenderId: '542509130475',
    projectId: 'elemanyonlendir-6c6b7',
    databaseURL: 'https://elemanyonlendir-6c6b7.firebaseio.com',
    storageBucket: 'elemanyonlendir-6c6b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb4oB4rWP6vqqYv_Ims8c0vLbePDWe--4',
    appId: '1:542509130475:ios:f27065c8905b80f45914ae',
    messagingSenderId: '542509130475',
    projectId: 'elemanyonlendir-6c6b7',
    databaseURL: 'https://elemanyonlendir-6c6b7.firebaseio.com',
    storageBucket: 'elemanyonlendir-6c6b7.appspot.com',
    iosClientId: '542509130475-cumn7fg5b03t7hc39po9gv0a4rp9c54o.apps.googleusercontent.com',
    iosBundleId: 'com.mysgrup.cleanermy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb4oB4rWP6vqqYv_Ims8c0vLbePDWe--4',
    appId: '1:542509130475:ios:50740281a03d6f1a5914ae',
    messagingSenderId: '542509130475',
    projectId: 'elemanyonlendir-6c6b7',
    databaseURL: 'https://elemanyonlendir-6c6b7.firebaseio.com',
    storageBucket: 'elemanyonlendir-6c6b7.appspot.com',
    iosClientId: '542509130475-kel54av01jqdalcoh1m2l69571c9scdl.apps.googleusercontent.com',
    iosBundleId: 'no',
  );
}
